module.exports = {
    INVALID_REQUEST : "Invalid request",
    BAD_REQUEST:'Bad Request',
    OUT_OF_BOUND:'out of bound or invalid',
    INVALID_EMAIL: "Email invalid",
    USER_VERIFIED: "User verified successfully",
    USER_NOT_VERIFIED: "User email not verified",
    USER_NOT_EXIST: "user not exist",
    USER_EXIST: "user already exist",
    USER_CREATED: "user created successfully",
    USER_EDITED: "user edited successfully",
    INVALID_PASSWORD: "Inavlid Password",
    USER_LOGGED_OUT:'user logged out successfully',
    QUESTION_OPTION_EMPTY:'Option should not be empty',
    QUESTION_OPTIONS_REQUIRED:'Atlest 2 options are required',
    PASSWORD_DONT_MATCH: "Password dosen't match",
    PASSWORD_CHANGED: "password changed successfully",
    INTERNAL_SERVER_ERROR:'Internal Server Error',
    INVALID_CREDENTIALS:'invalid credentials',
    USER_LOGEDIN:'User Logged in sucessfully',
    TOKEN_REQUIRED:"An authentication token is required",
    INVALID_TOKEN:'Invalid token',
}